---
  time_intervals:
    check_bt_login: 1 #min - ok VERIFICAR POR LOGIN
    time_refresh_position: 6 #min Sair e Entrar no mesmo mapa
    hero_full_work: 160
    hero_comum_work: 60
    hero_raro_work: 80 
    hero_sraro_work: 120
    hero_epico_work: 150 
    time_reboot_bot: 240
    #check_bt_map: 0.5 #min - ok TEMPO PARA VERIFICAR SE FOI FINALIZADO O MAPA E ENTRAR NO PROXIMO
